fragment HotelsParts on Hotels {
  __typename
  partner
  name
  stars
  location
  mainStreet
  addressNumber
  secondaryStreet
  contact {
    __typename
    type
    value
    tag
  }
  socialMedia {
    __typename
    name
    url
  }
  rooms {
    __typename
    name
    description_room {
      __typename
      lang_room
      content_destination
    }
    size
    occupancy {
      __typename
      min
      max
    }
    images
    room_services
  }
  roomPrice
  coverImage
  gallery
  description_hotel {
    __typename
    lang_hotel
    content_hotel
  }
  amenities {
    __typename
    basic_services
    general_services
    extra_services
    premium_services
  }
  highlight
}

fragment DestinationsParts on Destinations {
  __typename
  partner
  name
  location
  description_destination {
    __typename
    lang_destination
    content_destination
  }
  tags {
    __typename
    experience
    activities
    culture
    accessibility
    temporality
    popular
  }
  coverImage
  highlight
}

fragment OffersParts on Offers {
  __typename
  offer_id
  title
  coverImage
  description_offers {
    __typename
    lang_offer
    content_offer
  }
  expiration_date
  discount
  tags {
    __typename
    tag
  }
}
