// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI-powered hotel recommendation flow.
 *
 * - getHotelRecommendations - A function that generates personalized hotel recommendations.
 * - HotelRecommendationsInput - The input type for the getHotelRecommendations function.
 * - HotelRecommendationsOutput - The return type for the getHotelRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const HotelRecommendationsInputSchema = z.object({
  preferences: z
    .string()
    .describe('The user preferences for hotel like price range, location, amenities'),
  pastBookingHistory: z
    .string()
    .describe('The user past booking history in JSON format'),
  realTimeAvailability: z
    .string()
    .describe('The real time availability of hotels in JSON format'),
});
export type HotelRecommendationsInput = z.infer<typeof HotelRecommendationsInputSchema>;

const HotelRecommendationsOutputSchema = z.object({
  hotelRecommendations: z
    .string()
    .describe('The personalized hotel recommendations in JSON format'),
});
export type HotelRecommendationsOutput = z.infer<typeof HotelRecommendationsOutputSchema>;

export async function getHotelRecommendations(input: HotelRecommendationsInput): Promise<HotelRecommendationsOutput> {
  return hotelRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'hotelRecommendationsPrompt',
  input: {schema: HotelRecommendationsInputSchema},
  output: {schema: HotelRecommendationsOutputSchema},
  prompt: `You are an AI hotel recommendation expert. Based on the user preferences, booking history, and real-time availability,
you will generate personalized hotel recommendations in JSON format.

User Preferences: {{{preferences}}}
Past Booking History: {{{pastBookingHistory}}}
Real-time Availability: {{{realTimeAvailability}}}`,
});

const hotelRecommendationsFlow = ai.defineFlow(
  {
    name: 'hotelRecommendationsFlow',
    inputSchema: HotelRecommendationsInputSchema,
    outputSchema: HotelRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
